import { CarouselType } from '../NetflixComponent';

// CarouselMenu List 1
export const CarouselMenu1: CarouselType[] = [
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
];

export const CarouselMenu2: CarouselType[] = [
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
];
