import { CarouselType } from '../NetflixComponent';

// CarouselMenu List 1
export const CarouselMenu1: CarouselType[] = [
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '무인도의 디바', imgSrc: '/images/netflix/carousel/img01.webp' },
  { title: '힘쎈여자 강남순', imgSrc: '/images/netflix/carousel/img02.webp' },
  { title: '국민사형투표', imgSrc: '/images/netflix/carousel/img03.webp' },
  {
    title: '정신병동에도 아침이 와요',
    imgSrc: '/images/netflix/carousel/img04.jpg',
  },
  { title: '19/20', imgSrc: '/images/netflix/carousel/img05.jpg' },
  { title: '혜미리예채파', imgSrc: '/images/netflix/carousel/img06.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
];

export const CarouselMenu2: CarouselType[] = [
  { title: '진격의 거인', imgSrc: '/images/netflix/carousel/img13.webp' },
  { title: '주술회전', imgSrc: '/images/netflix/carousel/img14.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img15.webp' },
  {
    title: '스파이더맨',
    imgSrc: '/images/netflix/carousel/img16.webp',
  },
  { title: '고려거란전쟁', imgSrc: '/images/netflix/carousel/img17.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img18.webp' },
  { title: 'DP', imgSrc: '/images/netflix/carousel/img19.jpeg' },
  { title: '플루토', imgSrc: '/images/netflix/carousel/img20.jpeg' },
  { title: '최강야구', imgSrc: '/images/netflix/carousel/img21.webp' },
  { title: '장송의 프리렌', imgSrc: '/images/netflix/carousel/img22.webp' },
  { title: '좀비버스', imgSrc: '/images/netflix/carousel/img23.jpeg' },
  { title: '나의 행복한 결혼', imgSrc: '/images/netflix/carousel/img24.jpeg' },
  { title: '원피스', imgSrc: '/images/netflix/carousel/img25.jpeg' },
  { title: '응답하라 1988', imgSrc: '/images/netflix/carousel/img26.webp' },
  { title: '진격의 거인', imgSrc: '/images/netflix/carousel/img13.webp' },
  { title: '주술회전', imgSrc: '/images/netflix/carousel/img14.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img15.webp' },
  {
    title: '스파이더맨',
    imgSrc: '/images/netflix/carousel/img16.webp',
  },
  { title: '고려거란전쟁', imgSrc: '/images/netflix/carousel/img17.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img18.webp' },
  { title: 'DP', imgSrc: '/images/netflix/carousel/img19.jpeg' },
  { title: '플루토', imgSrc: '/images/netflix/carousel/img20.jpeg' },
  { title: '최강야구', imgSrc: '/images/netflix/carousel/img21.webp' },
  { title: '장송의 프리렌', imgSrc: '/images/netflix/carousel/img22.webp' },
  { title: '좀비버스', imgSrc: '/images/netflix/carousel/img23.jpeg' },
  { title: '나의 행복한 결혼', imgSrc: '/images/netflix/carousel/img24.jpeg' },
  { title: '원피스', imgSrc: '/images/netflix/carousel/img25.jpeg' },
  { title: '응답하라 1988', imgSrc: '/images/netflix/carousel/img26.webp' },
];

export const CarouselMenu3: CarouselType[] = [
  {
    title: '슈퍼마리오브라더스',
    imgSrc: '/images/netflix/carousel/img27.webp',
  },
  {
    title: '퀸카로 살아남는 법',
    imgSrc: '/images/netflix/carousel/img28.webp',
  },
  { title: '화이트칙스', imgSrc: '/images/netflix/carousel/img29.webp' },
  {
    title: '트와일라잇',
    imgSrc: '/images/netflix/carousel/img30.webp',
  },
  { title: '트루먼쇼', imgSrc: '/images/netflix/carousel/img31.webp' },
  { title: '불량공주 모모코', imgSrc: '/images/netflix/carousel/img32.webp' },
  { title: '스쿨오브락', imgSrc: '/images/netflix/carousel/img33.webp' },
  { title: '모노노케 히메', imgSrc: '/images/netflix/carousel/img34.webp' },
  { title: '중경삼림', imgSrc: '/images/netflix/carousel/img35.webp' },
  { title: '미녀 삼총사', imgSrc: '/images/netflix/carousel/img36.webp' },
  {
    title: '센과 치히로의 행방불명',
    imgSrc: '/images/netflix/carousel/img37.webp',
  },
  { title: '날씨의 아이', imgSrc: '/images/netflix/carousel/img38.webp' },
  {
    title: '하울의 움직이는 성',
    imgSrc: '/images/netflix/carousel/img39.webp',
  },
  { title: '벼랑 위의 포뇨', imgSrc: '/images/netflix/carousel/img40.webp' },
  { title: '라라랜드', imgSrc: '/images/netflix/carousel/img41.webp' },
  {
    title: '슈퍼마리오브라더스',
    imgSrc: '/images/netflix/carousel/img27.webp',
  },
  {
    title: '퀸카로 살아남는 법',
    imgSrc: '/images/netflix/carousel/img28.webp',
  },
  { title: '화이트칙스', imgSrc: '/images/netflix/carousel/img29.webp' },
  {
    title: '트와일라잇',
    imgSrc: '/images/netflix/carousel/img30.webp',
  },
  { title: '트루먼쇼', imgSrc: '/images/netflix/carousel/img31.webp' },
  { title: '불량공주 모모코', imgSrc: '/images/netflix/carousel/img32.webp' },
  { title: '스쿨오브락', imgSrc: '/images/netflix/carousel/img33.webp' },
  { title: '모노노케 히메', imgSrc: '/images/netflix/carousel/img34.webp' },
  { title: '중경삼림', imgSrc: '/images/netflix/carousel/img35.webp' },
  { title: '미녀 삼총사', imgSrc: '/images/netflix/carousel/img36.webp' },
  {
    title: '센과 치히로의 행방불명',
    imgSrc: '/images/netflix/carousel/img37.webp',
  },
  { title: '날씨의 아이', imgSrc: '/images/netflix/carousel/img38.webp' },
  {
    title: '하울의 움직이는 성',
    imgSrc: '/images/netflix/carousel/img39.webp',
  },
  { title: '벼랑 위의 포뇨', imgSrc: '/images/netflix/carousel/img40.webp' },
  { title: '라라랜드', imgSrc: '/images/netflix/carousel/img41.webp' },
];

export const CarouselMenu4: CarouselType[] = [
  { title: '고려거란전쟁', imgSrc: '/images/netflix/carousel/img17.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img18.webp' },
  { title: 'DP', imgSrc: '/images/netflix/carousel/img19.jpeg' },
  { title: '플루토', imgSrc: '/images/netflix/carousel/img20.jpeg' },
  { title: '최강야구', imgSrc: '/images/netflix/carousel/img21.webp' },
  { title: '장송의 프리렌', imgSrc: '/images/netflix/carousel/img22.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '불량공주 모모코', imgSrc: '/images/netflix/carousel/img32.webp' },
  { title: '스쿨오브락', imgSrc: '/images/netflix/carousel/img33.webp' },
  { title: '모노노케 히메', imgSrc: '/images/netflix/carousel/img34.webp' },
  { title: '중경삼림', imgSrc: '/images/netflix/carousel/img35.webp' },
  { title: '미녀 삼총사', imgSrc: '/images/netflix/carousel/img36.webp' },
  { title: '고려거란전쟁', imgSrc: '/images/netflix/carousel/img17.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img18.webp' },
  { title: 'DP', imgSrc: '/images/netflix/carousel/img19.jpeg' },
  { title: '플루토', imgSrc: '/images/netflix/carousel/img20.jpeg' },
  { title: '최강야구', imgSrc: '/images/netflix/carousel/img21.webp' },
  { title: '장송의 프리렌', imgSrc: '/images/netflix/carousel/img22.webp' },
  { title: '이두나!', imgSrc: '/images/netflix/carousel/img07.jpg' },
  { title: '아는형님', imgSrc: '/images/netflix/carousel/img08.webp' },
  { title: '하이쿠키', imgSrc: '/images/netflix/carousel/img09.webp' },
  { title: '오늘도 사랑스럽개', imgSrc: '/images/netflix/carousel/img10.webp' },
  { title: '그해우리는', imgSrc: '/images/netflix/carousel/img11.webp' },
  { title: '혼례대첩', imgSrc: '/images/netflix/carousel/img12.webp' },
  { title: '불량공주 모모코', imgSrc: '/images/netflix/carousel/img32.webp' },
  { title: '스쿨오브락', imgSrc: '/images/netflix/carousel/img33.webp' },
  { title: '모노노케 히메', imgSrc: '/images/netflix/carousel/img34.webp' },
  { title: '중경삼림', imgSrc: '/images/netflix/carousel/img35.webp' },
  { title: '미녀 삼총사', imgSrc: '/images/netflix/carousel/img36.webp' },
];
